export const GETHISTORY="GETHISTORY";

export const FAILUREHISTORY="FAILUREHISTORY";

export const SUCCESSEXPENSEHISTORY="SUCCESSEXPENSEHISTORY";

export const ADDEXPENSEDATA="ADDEXPENSEDATA";

export const REMOVEEXPENSE="REMOVEEXPENSE";