
export const GETHISTORY="GETHISTORY";

export const SUCCESSINCOMEHISTORY="SUCCESSINCOMEHISTORY";

export const FAILUREHISTORY="FAILUREHISTORY";

export const SUCCESSEXPENSEHISTORY="SUCCESSEXPENSEHISTORY";

export const ADDINCOMEDATA="ADDINCOMEDATA";

export const REMOVEINCOME="REMOVEINCOME";
